### ISSUE TITLE
Wider release

### ISSUE THREAD

**Issue by yfdyh000** [bwinton/quick-load#1]
@bwinton Hi, I think this project is a creative idea. Why don't you publish it as an add-on to AMO or Test Pilot?

**Comment by bwinton** [comment]
We have a team working on perceived performance ideas like this, so hopefully it will just happen in Firefox itself.  🙂

Thanks for the suggestion!

**Comment by yfdyh000** [comment]
Thank you for your answer, I look forward to it.
